name: Setup Environment
description: Does minimal setup of environment for a job

runs:
  using: composite
  steps:
    - name: Add extra required branches
      if: ${{ github.event_name == 'pull_request' }}
      run: git fetch origin ${{ github.event.pull_request.base.ref }}:${{ github.event.pull_request.base.ref }}
      shell: bash

    - name: Use Node.js from nvmrc file
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'

    - name: Restore lerna cache
      id: lerna-npm-cache
      uses: actions/cache@v4
      with:
        path: '**/node_modules'
        key: ${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      if: steps.lerna-npm-cache.outputs.cache-hit != 'true'
      run: npm ci
      shell: bash